#!/usr/bin/env bash
# A script to check the network connectivity to a given IP address,
# and send 5 pings (ICMP packets) to this IP address to test the connection.

if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 "$1"
